name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # You can keep this, or switch to another runner if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # This step uses a GitHub Action to checkout your code

      - name: Set up Python 3.12
        uses: actions/setup-python@v4  # This step uses a GitHub Action to set up Python
        with:
          python-version: '3.12'  # Using Python 3.12.3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # This is a shell command to upgrade pip
          pip install -r requirements.txt  # Install dependencies listed in requirements.txt

      - name: Run tests
        run: |
          pytest  # This is a shell command to run the tests with pytest
